### ISSUE TITLE
home: portfolio cards stretched in narrow view

### ISSUE THREAD

**Issue by bendichter** [davewibisono/catalyst-neuro#15]
<img width="841" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/247967cc-876a-4e77-94d5-f2a7086b8573">

**Comment by davewibisono** [comment]
Fixed. Done

**Comment by bendichter** [comment]
This is still broken

<img width="1115" alt="image" src="https://github.com/davewibisono/catalyst-neuro/assets/844306/64f6f392-ccef-4b6e-8ad5-1282b8fb4706">
